/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as PostsIdRouteImport } from './routes/posts/$id'
import { Route as OauthCallbackRouteImport } from './routes/oauth/callback'
import { Route as UsersUserIdIndexRouteImport } from './routes/users/$userId.index'
import { Route as UsersUserIdFollowingRouteImport } from './routes/users/$userId.following'
import { Route as UsersUserIdFollowersRouteImport } from './routes/users/$userId.followers'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIdRoute = PostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdIndexRoute = UsersUserIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersUserIdRoute,
} as any)
const UsersUserIdFollowingRoute = UsersUserIdFollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => UsersUserIdRoute,
} as any)
const UsersUserIdFollowersRoute = UsersUserIdFollowersRouteImport.update({
  id: '/followers',
  path: '/followers',
  getParentRoute: () => UsersUserIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/posts/$id': typeof PostsIdRoute
  '/u/$username': typeof UUsernameRoute
  '/users/$userId': typeof UsersUserIdRouteWithChildren
  '/users/$userId/followers': typeof UsersUserIdFollowersRoute
  '/users/$userId/following': typeof UsersUserIdFollowingRoute
  '/users/$userId/': typeof UsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/posts/$id': typeof PostsIdRoute
  '/u/$username': typeof UUsernameRoute
  '/users/$userId/followers': typeof UsersUserIdFollowersRoute
  '/users/$userId/following': typeof UsersUserIdFollowingRoute
  '/users/$userId': typeof UsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/posts/$id': typeof PostsIdRoute
  '/u/$username': typeof UUsernameRoute
  '/users/$userId': typeof UsersUserIdRouteWithChildren
  '/users/$userId/followers': typeof UsersUserIdFollowersRoute
  '/users/$userId/following': typeof UsersUserIdFollowingRoute
  '/users/$userId/': typeof UsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookmarks'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/search'
    | '/settings'
    | '/oauth/callback'
    | '/posts/$id'
    | '/u/$username'
    | '/users/$userId'
    | '/users/$userId/followers'
    | '/users/$userId/following'
    | '/users/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookmarks'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/search'
    | '/settings'
    | '/oauth/callback'
    | '/posts/$id'
    | '/u/$username'
    | '/users/$userId/followers'
    | '/users/$userId/following'
    | '/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/bookmarks'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/search'
    | '/settings'
    | '/oauth/callback'
    | '/posts/$id'
    | '/u/$username'
    | '/users/$userId'
    | '/users/$userId/followers'
    | '/users/$userId/following'
    | '/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookmarksRoute: typeof BookmarksRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  PostsIdRoute: typeof PostsIdRoute
  UUsernameRoute: typeof UUsernameRoute
  UsersUserIdRoute: typeof UsersUserIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId/': {
      id: '/users/$userId/'
      path: '/'
      fullPath: '/users/$userId/'
      preLoaderRoute: typeof UsersUserIdIndexRouteImport
      parentRoute: typeof UsersUserIdRoute
    }
    '/users/$userId/following': {
      id: '/users/$userId/following'
      path: '/following'
      fullPath: '/users/$userId/following'
      preLoaderRoute: typeof UsersUserIdFollowingRouteImport
      parentRoute: typeof UsersUserIdRoute
    }
    '/users/$userId/followers': {
      id: '/users/$userId/followers'
      path: '/followers'
      fullPath: '/users/$userId/followers'
      preLoaderRoute: typeof UsersUserIdFollowersRouteImport
      parentRoute: typeof UsersUserIdRoute
    }
  }
}

interface UsersUserIdRouteChildren {
  UsersUserIdFollowersRoute: typeof UsersUserIdFollowersRoute
  UsersUserIdFollowingRoute: typeof UsersUserIdFollowingRoute
  UsersUserIdIndexRoute: typeof UsersUserIdIndexRoute
}

const UsersUserIdRouteChildren: UsersUserIdRouteChildren = {
  UsersUserIdFollowersRoute: UsersUserIdFollowersRoute,
  UsersUserIdFollowingRoute: UsersUserIdFollowingRoute,
  UsersUserIdIndexRoute: UsersUserIdIndexRoute,
}

const UsersUserIdRouteWithChildren = UsersUserIdRoute._addFileChildren(
  UsersUserIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookmarksRoute: BookmarksRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  PostsIdRoute: PostsIdRoute,
  UUsernameRoute: UUsernameRoute,
  UsersUserIdRoute: UsersUserIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
